// TYPES FOR FETCHING DATA
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
// TYPES FOR ADD & REMOVE FROM HOME COMPONENT
export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const REMOVE_ALL_CART = 'REMOVE_ALL_CART';
// TYPES FOR SORT & FILTER PRODUCTS
export const SORT_VALUE = 'SORT_VALUE';
export const FILTER_VALUE = 'FILTER_VALUE';
// TYPES FOR RESET DATA FROM CART COMPONENT
export const RESET_CART = 'RESET_CART';
export const ITEM_QUANTITY = 'ITEM_QUANTITY';
// TYPES FOR ADMIN ACTIONS
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const RESET_DEFAULT_PRODUCT = 'RESET_DEFAULT_PRODUCT';
